local obj = {}

obj.name = "EasySanskrit for macOS"
obj.version = "1.0.0"
obj.author = "Takahiro Kawaji"
obj.license = "MIT"

-- User-configurable hotkey / ユーザーが init.lua から変更できるホットキー
-- Default: Control + Command + E / デフォルト：Control + Command + E
obj.toggleHotkey = {{"ctrl", "cmd"}, "E"}

local tap = nil
local toggleBinding = nil
local buffer = ""
local injecting = false
local enabled = true

-- Time window for "=" after r. / l. (seconds)
-- r. / l. の後に "=" を待つ時間（秒）
local vocalicTimeout = 3.0
local pendingVocalic = nil
local vocalicTimer = nil

-- Replace previously entered characters with the specified text
-- 直前に入力された文字を削除し、指定された文字列に置換する
local function replacePreviousChars(count, text)
    injecting = true

    for _ = 1, count do
        hs.eventtap.keyStroke({}, "delete", 0)
    end

    hs.eventtap.keyStrokes(text)

    hs.timer.doAfter(0.05, function()
        injecting = false
    end)
end

-- Standard two-character conversions
-- 通常の2文字変換
local replacements = {
    -- Vowels / 母音
    ["a="] = hs.utf8.char(0x0101), -- ā
    ["A="] = hs.utf8.char(0x0100), -- Ā
    ["i="] = hs.utf8.char(0x012B), -- ī
    ["I="] = hs.utf8.char(0x012A), -- Ī
    ["u="] = hs.utf8.char(0x016B), -- ū
    ["U="] = hs.utf8.char(0x016A), -- Ū

    -- Consonants / 子音
    ["t."] = hs.utf8.char(0x1E6D), -- ṭ
    ["T."] = hs.utf8.char(0x1E6C), -- Ṭ
    ["d."] = hs.utf8.char(0x1E0D), -- ḍ
    ["D."] = hs.utf8.char(0x1E0C), -- Ḍ
    ["n."] = hs.utf8.char(0x1E47), -- ṇ
    ["N."] = hs.utf8.char(0x1E46), -- Ṇ
    ["s."] = hs.utf8.char(0x1E63), -- ṣ
    ["S."] = hs.utf8.char(0x1E62), -- Ṣ

    ["n^"] = hs.utf8.char(0x1E45), -- ṅ
    ["N^"] = hs.utf8.char(0x1E44), -- Ṅ

    ["n~"] = hs.utf8.char(0x00F1), -- ñ
    ["N~"] = hs.utf8.char(0x00D1), -- Ñ

    ["s'"] = hs.utf8.char(0x015B), -- ś
    ["S'"] = hs.utf8.char(0x015A), -- Ś

    -- Anusvāra / アヌスヴァーラ
    ["m."] = hs.utf8.char(0x1E43), -- ṃ
    ["M."] = hs.utf8.char(0x1E42), -- Ṃ

    -- Visarga / ヴィサルガ
    ["h."] = hs.utf8.char(0x1E25), -- ḥ
    ["H."] = hs.utf8.char(0x1E24)  -- Ḥ
}

-- Vocalic r/l conversions
-- ṛ・ṝ・ḷ・ḹ などの変換
local vocalics = {
    ["r."] = {
        short = hs.utf8.char(0x1E5B), -- ṛ
        long  = hs.utf8.char(0x1E5D)  -- ṝ
    },

    ["R."] = {
        short = hs.utf8.char(0x1E5A), -- Ṛ
        long  = hs.utf8.char(0x1E5C)  -- Ṝ
    },

    ["l."] = {
        short = hs.utf8.char(0x1E37), -- ḷ
        long  = hs.utf8.char(0x1E39)  -- ḹ
    },

    ["L."] = {
        short = hs.utf8.char(0x1E36), -- Ḷ
        long  = hs.utf8.char(0x1E38)  -- Ḹ
    }
}

-- Anunāsika-related characters
-- アヌナーシカ関連
local nasalization = {
    ["m~"] = "m" .. hs.utf8.char(0x0310), -- m̐
    ["M~"] = "M" .. hs.utf8.char(0x0310), -- M̐

    ["y~"] = "y" .. hs.utf8.char(0x0303), -- ỹ
    ["Y~"] = "Y" .. hs.utf8.char(0x0303), -- Ỹ

    ["l~"] = "l" .. hs.utf8.char(0x0303), -- l̃
    ["L~"] = "L" .. hs.utf8.char(0x0303), -- L̃

    ["v~"] = "v" .. hs.utf8.char(0x0303), -- ṽ
    ["V~"] = "V" .. hs.utf8.char(0x0303)  -- Ṽ
}

-- Special symbols
-- 特殊記号
-- Longer triggers must be checked first
-- 長い入力文字列から先に判定する
local symbols = {
    {
        trigger = "||.",
        output = hs.utf8.char(0x0965) -- Double danda / ダブルダンダ ॥
    },
    {
        trigger = "|.",
        output = hs.utf8.char(0x0964) -- Danda / ダンダ ।
    },
    {
        trigger = "''",
        output = hs.utf8.char(0x2019) -- Avagraha / アヴァグラハ ’
    }
}

-- Clear pending vocalic conversion
-- Vocalic変換の待機状態を解除する
local function clearPendingVocalic()
    pendingVocalic = nil

    if vocalicTimer then
        vocalicTimer:stop()
        vocalicTimer = nil
    end
end

-- Start waiting for "=" after ṛ / Ṛ / ḷ / Ḷ
-- ṛ / Ṛ / ḷ / Ḷ の入力後、"=" の入力を待機する
local function beginPendingVocalic(data)
    clearPendingVocalic()
    pendingVocalic = data

    vocalicTimer = hs.timer.doAfter(vocalicTimeout, function()
        pendingVocalic = nil
        vocalicTimer = nil
    end)
end

-- Enable or disable EasySanskrit conversion
-- EasySanskritの変換を一時停止・再開する
local function toggleEnabled()
    enabled = not enabled
    buffer = ""
    clearPendingVocalic()

    if enabled then
        hs.alert.show("EasySanskrit: ON")
    else
        hs.alert.show("EasySanskrit: OFF")
    end
end

-- Start EasySanskrit
-- EasySanskritを開始する
function obj:start()
    if tap then
        return self
    end

    enabled = true

    tap = hs.eventtap.new(
        {hs.eventtap.event.types.keyDown},
        function(event)

            -- Ignore events generated by EasySanskrit itself or while disabled
            -- EasySanskrit自身が生成した入力、および一時停止中の入力は処理しない
            if injecting or not enabled then
                return false
            end

            local chars = event:getCharacters()

            if not chars or chars == "" then
                return false
            end

            -- If "=" is entered immediately after ṛ / Ṛ / ḷ / Ḷ,
            -- replace it with the corresponding long form
            -- ṛ / Ṛ / ḷ / Ḷ の直後に "=" が入力された場合、
            -- 対応する長母音形に置換する
            if pendingVocalic then
                if chars == "=" then
                    local longChar = pendingVocalic.long

                    clearPendingVocalic()

                    hs.timer.doAfter(0, function()
                        replacePreviousChars(1, longChar)
                    end)

                    buffer = ""
                    return true
                else
                    clearPendingVocalic()
                end
            end

            buffer = buffer .. chars

            if #buffer > 6 then
                buffer = buffer:sub(-6)
            end

            -- Special symbols / 特殊記号
            for _, item in ipairs(symbols) do
                local trigger = item.trigger

                if buffer:sub(-#trigger) == trigger then
                    hs.timer.doAfter(0, function()
                        replacePreviousChars(#trigger - 1, item.output)
                    end)

                    buffer = ""
                    return true
                end
            end

            -- Vocalic r/l / ṛ・ṝ・ḷ・ḹ など
            for trigger, data in pairs(vocalics) do
                if buffer:sub(-#trigger) == trigger then
                    hs.timer.doAfter(0, function()
                        replacePreviousChars(#trigger - 1, data.short)
                    end)

                    beginPendingVocalic(data)
                    buffer = ""
                    return true
                end
            end

            -- Anunāsika-related characters / アヌナーシカ関連
            for trigger, output in pairs(nasalization) do
                if buffer:sub(-#trigger) == trigger then
                    hs.timer.doAfter(0, function()
                        replacePreviousChars(#trigger - 1, output)
                    end)

                    buffer = ""
                    return true
                end
            end

            -- Standard conversions / 通常変換
            for trigger, output in pairs(replacements) do
                if buffer:sub(-#trigger) == trigger then
                    hs.timer.doAfter(0, function()
                        replacePreviousChars(#trigger - 1, output)
                    end)

                    buffer = ""
                    return true
                end
            end

            return false
        end
    )

    tap:start()

    -- Register the toggle hotkey
    -- 一時停止・再開用ホットキーを登録する
    if obj.toggleHotkey then
        toggleBinding = hs.hotkey.bindSpec(
            obj.toggleHotkey,
            toggleEnabled
        )
    end

    hs.alert.show("EasySanskrit for macOS started")

    return self
end

-- Stop EasySanskrit
-- EasySanskritを終了する
function obj:stop()
    if tap then
        tap:stop()
        tap = nil
    end

    if toggleBinding then
        toggleBinding:delete()
        toggleBinding = nil
    end

    clearPendingVocalic()
    buffer = ""
    enabled = false

    hs.alert.show("EasySanskrit for macOS stopped")

    return self
end

return obj
